asset: gitup-darwin-386.tgz
tap: kdisneur/homebrew-formulae/Formula/gitup.rb
template: |
  class Gitup < Formula
    desc     "$REPO_DESCRIPTION"
    homepage "$REPO_WEBSITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_URL"
    sha256   "$STABLE_SHA256"

    def install
      bin.install "gitup"
    end
  end
